# Generated by Django 3.0.6 on 2020-05-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True)),
                ('editado', models.DateField(auto_now=True)),
                ('descricao', models.CharField(max_length=255)),
                ('quantidade', models.IntegerField(max_length=4)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
