# Generated by Django 3.0.6 on 2020-05-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notemarket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='quantidade',
            field=models.IntegerField(),
        ),
    ]
